BANKS_SEED = [
    {
        "id": "sbi",
        "name": "State Bank of India",
        "short_name": "SBI",
        "type": "Public",
        "interest_min": 8.5,
        "interest_max": 11.0,
        "max_funding": 100000000,
        "processing_fee_percent": 0.35,
        "min_credit_score": 700,
        "collateral_required": True,
        "supports": ["MSME", "PMEGP", "Mudra", "Stand-Up India", "CGTMSE"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "India's largest public sector bank. Strong presence across MSME, agriculture and government scheme lending.",
        "why": "Best for PMEGP, Mudra and large-ticket MSME loans with collateral. Wide branch network across India.",
        "min_turnover": 0,
    },
    {
        "id": "bob",
        "name": "Bank of Baroda",
        "short_name": "BoB",
        "type": "Public",
        "interest_min": 8.6,
        "interest_max": 11.5,
        "max_funding": 50000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "Mudra", "Stand-Up India", "CGTMSE"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "Public sector bank with strong MSME and women entrepreneur lending programs.",
        "why": "Competitive rates for Mudra and Stand-Up India loans. Good for women entrepreneurs.",
        "min_turnover": 0,
    },
    {
        "id": "canara",
        "name": "Canara Bank",
        "short_name": "Canara",
        "type": "Public",
        "interest_min": 8.7,
        "interest_max": 12.0,
        "max_funding": 50000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "PMEGP", "Mudra"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "Strong south-India presence with dedicated MSME and agriculture lending desks.",
        "why": "Preferred for MSME manufacturing units in south India.",
        "min_turnover": 0,
    },
    {
        "id": "pnb",
        "name": "Punjab National Bank",
        "short_name": "PNB",
        "type": "Public",
        "interest_min": 8.55,
        "interest_max": 11.75,
        "max_funding": 75000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "Mudra", "PMEGP", "Stand-Up India"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "Major public sector bank with deep MSME network in North India.",
        "why": "Strong reach in Punjab, Delhi, Haryana, UP — good for traders & manufacturers.",
        "min_turnover": 0,
    },
    {
        "id": "union",
        "name": "Union Bank of India",
        "short_name": "Union",
        "type": "Public",
        "interest_min": 8.7,
        "interest_max": 12.0,
        "max_funding": 50000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "Mudra", "CGTMSE"],
        "industries": ["Manufacturing", "Service", "Trading"],
        "states": ["All India"],
        "description": "Public sector bank actively servicing MSMEs in Maharashtra, Karnataka, Telangana.",
        "why": "Good for service & trading businesses with CGTMSE-backed collateral-free loans.",
        "min_turnover": 0,
    },
    {
        "id": "indian-bank",
        "name": "Indian Bank",
        "short_name": "Indian Bank",
        "type": "Public",
        "interest_min": 8.65,
        "interest_max": 11.9,
        "max_funding": 40000000,
        "processing_fee_percent": 0.5,
        "min_credit_score": 680,
        "collateral_required": True,
        "supports": ["MSME", "Mudra", "PMEGP"],
        "industries": ["Manufacturing", "Service", "Trading", "Agriculture"],
        "states": ["All India"],
        "description": "South-India focused public sector bank with strong PMEGP and Mudra delivery.",
        "why": "Quick disbursal for Mudra Shishu/Kishore loans.",
        "min_turnover": 0,
    },
    {
        "id": "hdfc",
        "name": "HDFC Bank",
        "short_name": "HDFC",
        "type": "Private",
        "interest_min": 10.0,
        "interest_max": 16.0,
        "max_funding": 75000000,
        "processing_fee_percent": 1.5,
        "min_credit_score": 720,
        "collateral_required": False,
        "supports": ["MSME", "Business Loan", "Working Capital"],
        "industries": ["Manufacturing", "Service", "Trading"],
        "states": ["All India"],
        "description": "Largest private bank. Fast turnaround for unsecured business loans up to ₹75 lakhs.",
        "why": "Best for established businesses needing unsecured working capital with quick disbursal.",
        "min_turnover": 1500000,
    },
    {
        "id": "icici",
        "name": "ICICI Bank",
        "short_name": "ICICI",
        "type": "Private",
        "interest_min": 10.5,
        "interest_max": 17.0,
        "max_funding": 100000000,
        "processing_fee_percent": 2.0,
        "min_credit_score": 720,
        "collateral_required": False,
        "supports": ["MSME", "Business Loan", "Working Capital", "CGTMSE"],
        "industries": ["Manufacturing", "Service", "Trading"],
        "states": ["All India"],
        "description": "Private bank with strong digital onboarding for MSME and business loans.",
        "why": "Quick digital sanction (24-48 hrs) for businesses with GST + Udyam.",
        "min_turnover": 2000000,
    },
    {
        "id": "axis",
        "name": "Axis Bank",
        "short_name": "Axis",
        "type": "Private",
        "interest_min": 10.5,
        "interest_max": 17.5,
        "max_funding": 50000000,
        "processing_fee_percent": 2.0,
        "min_credit_score": 720,
        "collateral_required": False,
        "supports": ["MSME", "Business Loan", "Working Capital"],
        "industries": ["Service", "Trading", "Manufacturing"],
        "states": ["All India"],
        "description": "Private sector bank with competitive unsecured business loans.",
        "why": "Good for service businesses with strong GST returns and bank statements.",
        "min_turnover": 1500000,
    },
]
